# SPDX-License-Identifier: PMPL-1.0
# SPDX-FileCopyrightText: 2025 Jonathan D. A. Jewell <hyperpolymath>
#
# Podman Pod Definition for Project Wharf (Yacht Runtime)
# ========================================================
# Two-container architecture: OpenLiteSpeed (web+PHP) + Agent (security)
#
# Legacy path (development only):
# Deploy: podman kube play infra/podman/yacht.yaml
# Remove: podman kube down infra/podman/yacht.yaml
#
# Preferred path (production): use infra/svalinn/yacht.yaml with
# Svalinn + Vordr + Cerro Torre images and attestations.
#
# Architecture:
# - web: OpenLiteSpeed + PHP 8.3 (LSAPI) - serves WordPress
# - agent: Yacht Agent (distroless Rust) - DB proxy, integrity, eBPF loader
#
# Security Model:
# - Web root is READ-ONLY (immutable)
# - Only /wp-content/uploads is writable
# - Database access is proxied and filtered by Agent
# - /wp-admin is blocked at web server level (Dark Matter)

apiVersion: v1
kind: Pod
metadata:
  name: yacht
  labels:
    app: wharf
    component: yacht
    version: "1.0.0"
  annotations:
    wharf.io/security-level: "immutable"
    wharf.io/admin-access: "offline-only"
spec:
  # Containers share localhost networking
  hostNetwork: false

  # Restart policy
  restartPolicy: Always

  containers:
    # =========================================================================
    # 1. WEB SERVER - OpenLiteSpeed + PHP (LSAPI)
    # =========================================================================
    - name: web
      image: localhost/yacht-web:latest
      ports:
        - containerPort: 8080
          hostPort: 80
          protocol: TCP
        - containerPort: 8443
          hostPort: 443
          protocol: TCP
      resources:
        limits:
          memory: "512Mi"
          cpu: "1000m"
        requests:
          memory: "256Mi"
          cpu: "250m"
      securityContext:
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: false  # OLS needs to write to logs/tmp
        capabilities:
          drop:
            - ALL
      volumeMounts:
        # Web root - READ ONLY (immutable files from Wharf)
        - name: web-root
          mountPath: /var/www/html
          readOnly: true
        # Uploads - WRITABLE (user-generated content)
        - name: uploads
          mountPath: /var/www/html/wp-content/uploads
          readOnly: false
        # LiteSpeed cache - RAM disk
        - name: lscache
          mountPath: /dev/shm/lscache
        # SSL certificates
        - name: certs
          mountPath: /etc/letsencrypt
          readOnly: true
      env:
        # Database connection (routed through Agent proxy on localhost)
        - name: DB_HOST
          value: "127.0.0.1"
        - name: DB_PORT
          value: "3306"
        # Redis for sessions/object cache (if available)
        - name: REDIS_HOST
          value: "127.0.0.1"
        - name: REDIS_PORT
          value: "6379"
      livenessProbe:
        httpGet:
          path: /health
          port: 8080
        initialDelaySeconds: 10
        periodSeconds: 10
        timeoutSeconds: 3
      readinessProbe:
        httpGet:
          path: /health
          port: 8080
        initialDelaySeconds: 5
        periodSeconds: 5

    # =========================================================================
    # 2. YACHT AGENT - Security Enforcer (Distroless)
    # =========================================================================
    - name: agent
      image: localhost/yacht-agent:latest
      ports:
        # DB Proxy (MySQL wire protocol masquerade)
        - containerPort: 3306
          protocol: TCP
        # Agent API (health, metrics, mooring endpoint)
        - containerPort: 9001
          protocol: TCP
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
        requests:
          memory: "64Mi"
          cpu: "100m"
      securityContext:
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        capabilities:
          # Required for eBPF loading (optional - graceful fallback to nftables)
          add:
            - NET_ADMIN
            - BPF
          drop:
            - ALL
      volumeMounts:
        # Agent config (database policy, firewall rules)
        - name: agent-config
          mountPath: /etc/wharf
          readOnly: true
        # Integrity manifest storage
        - name: integrity-db
          mountPath: /var/lib/wharf
          readOnly: false
      env:
        # Real database location (shadow port)
        - name: SHADOW_DB_HOST
          value: "yacht-db"
        - name: SHADOW_DB_PORT
          value: "33060"
        # Protocol (mysql or postgres)
        - name: DB_PROTOCOL
          value: "mysql"
        # Network interface for eBPF (if available)
        - name: XDP_INTERFACE
          value: "eth0"
        # Firewall mode: ebpf, nftables, or none
        - name: FIREWALL_MODE
          value: "nftables"
        # Metrics endpoint
        - name: METRICS_ENABLED
          value: "true"
      # TCP probe since distroless has no curl/wget
      livenessProbe:
        tcpSocket:
          port: 9001
        initialDelaySeconds: 5
        periodSeconds: 10
      readinessProbe:
        tcpSocket:
          port: 3306
        initialDelaySeconds: 3
        periodSeconds: 5

  # ===========================================================================
  # VOLUMES
  # ===========================================================================
  volumes:
    # The website files (pushed from Wharf)
    - name: web-root
      hostPath:
        path: /opt/wharf/sites/default/html
        type: Directory

    # Uploads directory (writable by PHP for media uploads)
    - name: uploads
      hostPath:
        path: /opt/wharf/sites/default/uploads
        type: DirectoryOrCreate

    # Agent configuration (compiled from Nickel/TOML)
    - name: agent-config
      hostPath:
        path: /opt/wharf/config
        type: Directory

    # Integrity database (BLAKE3 manifests)
    - name: integrity-db
      hostPath:
        path: /opt/wharf/integrity
        type: DirectoryOrCreate

    # SSL/TLS certificates
    - name: certs
      hostPath:
        path: /opt/wharf/certs
        type: DirectoryOrCreate

    # LiteSpeed Cache (RAM disk)
    - name: lscache
      emptyDir:
        medium: Memory
        sizeLimit: "256Mi"

---
# ===========================================================================
# DATABASE POD (Separate for isolation)
# ===========================================================================
# The database runs on a "shadow port" (33060) not the standard 3306.
# The Agent proxies 3306 -> 33060, filtering queries via AST analysis.

apiVersion: v1
kind: Pod
metadata:
  name: yacht-db
  labels:
    app: wharf
    component: database
spec:
  restartPolicy: Always

  containers:
    - name: mariadb
      image: registry.cerro-torre.local/wharf/mariadb:0.1.0
      ports:
        # Shadow port (not exposed externally)
        - containerPort: 3306
          hostPort: 33060
          protocol: TCP
      resources:
        limits:
          memory: "1Gi"
          cpu: "1000m"
        requests:
          memory: "256Mi"
          cpu: "250m"
      securityContext:
        runAsNonRoot: true
        allowPrivilegeEscalation: false
      volumeMounts:
        - name: db-data
          mountPath: /var/lib/mysql
        - name: db-config
          mountPath: /etc/mysql/conf.d
          readOnly: true
      env:
        - name: MYSQL_DATABASE
          value: "wordpress"
        - name: MYSQL_USER
          value: "wordpress"
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: password
              optional: true
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: root-password
              optional: true
      livenessProbe:
        exec:
          command: ["mysqladmin", "ping", "-h", "localhost", "-u", "root"]
        initialDelaySeconds: 30
        periodSeconds: 10
      readinessProbe:
        exec:
          command: ["mysqladmin", "ping", "-h", "localhost", "-u", "root"]
        initialDelaySeconds: 10
        periodSeconds: 5

  volumes:
    - name: db-data
      hostPath:
        path: /opt/wharf/data/mysql
        type: DirectoryOrCreate
    - name: db-config
      hostPath:
        path: /opt/wharf/config/mysql
        type: DirectoryOrCreate

---
# ===========================================================================
# SECRET TEMPLATE (Create before deploying)
# ===========================================================================
# Create with: podman secret create db-credentials credentials.env
#
# credentials.env:
#   password=your-secure-wordpress-password
#   root-password=your-secure-root-password

apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
stringData:
  password: "CHANGE_ME_wordpress_password"
  root-password: "CHANGE_ME_root_password"
